/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e235738;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.ArrayList;

public class GameMasterTest {
    @Test 
    public void appHasAGreeting() {
        ArrayList<String> time = new ArrayList<>();
        time.add("朝");
        time.add("昼");
        time.add("夜");
        GameMaster Game = new GameMaster(time);
        assertEquals(Game.time.get(0),"朝" );
    }
}
